# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: About software development that make sense
email: s2lomon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog regarding topic like Java/Java8, rx-java, reactor, reactive programming, CQRS, NoSQL,
  TDD, BDD, DDD, modeling, analysis, CleanCode, SOLID, CI, CD Evolutionary Architecture, YAGNI(sic!) etc.
  In one sentence - it's about software development that make sense.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://techbites.net" # the base hostname & protocol for your site
twitter_username: s2lomon
github_username:  s2lomon

gems: [jekyll-paginate]

excerpt_separator: <!--more-->
paginate: 5

# Build settings
markdown: kramdown


