# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Szymon Homa
subtitle: about software and things
email: s2lomon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Main topics that this blog should tackle are: Java/Java8, rx-java, reactor, reactive programming, CQRS, NoSQL,
  TDD, BDD, DDD, modeling, analysis, CleanCode, SOLID, CI, CD, Evolutionary Architecture and so on.

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://szymonhoma.com" # the base hostname & protocol for your site
twitter_username: s2lomon
github_username:  s2lomon
linkedin_profile_uri: szymon-homa-515ba85b

gems: [jekyll-paginate]

excerpt_separator: <!--more-->
paginate: 5

# Build settings
markdown: kramdown


