#!/bin/sh
#This script deals with the fact github pages does not allow all jekyll features. To overcome that, one can host jekyll page from plain html sources,
#which is exactly what resieds in _site folder, that's generated by jekyll. This script copies all that resides in _site folder to root folder on master branch

echo "switching to master"
git checkout master
echo "moving all _site to current folder"
cp -r _site/* . && touch .nojekyll
echo "moved all _site to current folder"
